### PR TITLE
About page

### PR DESCRIPTION
**Pull request by kalidiagne**
About page 

**Desktop 1** 

Screenshot 2023-09-07 at 13 35 29

**Mobile 1** 

Screenshot 2023-09-07 at 13 34 56

**Mobile 2**

Screenshot 2023-09-07 at 13 47 48

**Mobile 3**

Screenshot 2023-09-07 at 13 37 58

### CODE REVIEW

**Review by ChialiT — COMMENTED** [review]
@kalidiagne I think these function well, let's try different padding instead of flex 100%.
maybe can use project lib as standard, so all the content are just centered in a fixed container.

This is from my monitor :)
image

**Comment by kalidiagne** [comment]
@ChialiT @AtHeartEngineer PR updated can you please check again?

**Comment by ChialiT** [comment]
I think the padding can be better, but its ok, we will do a overhaul after v2.4.

**Review by ChialiT — APPROVED** [review]

**Comment by thebeyondr** [comment]
@kalidiagne this works but I don't think the accordion animations are firing

**Review by thebeyondr — APPROVED** [review]

**Comment by kalidiagne** [comment]
> @kalidiagne this works but I don't think the accordion animations are firing

Oh, that's a good point! added animation an merging :)

**Pull request merged**
