### PR TITLE
add filters

### PR DESCRIPTION
**Pull request by kalidiagne**
This PR adds the ability to use filters for the `project library`, it also include tags in the project details page.

### CODE REVIEW

**Comment by thebeyondr** [comment]
@kalidiagne - Almost ready! just a few things:

## Filters

- "Show projects" would be better here when initiating a filter in the modal
image

- Shouldn't users be able to add all of these? Right now we can only filter with one at a time, so users can't filter by Build & Play at this time.
image

- "Clear all" in the modal resets the Build/Play/Research as well. Unsure if this expected behavior or it should be to reset the filters in the modal only

- Modal: The filter is triggered on every tag checked instead of when "Show projects" is clicked. I think users should be able to select all they want and then have one trigger to make it happen.


## On mobile

- Decreasing the padding and icon sizes would allow for these buttons to get more room
image

- We could decrease the padding on these tags as well as the container
image

**Comment by ChialiT** [comment]
> * Shouldn't users be able to add all of these? Right now we can only filter with one at a time, so users can't filter by Build & Play at this time.
>   image

the theme filter logic, we have decided just one at a time.

**Comment by ChialiT** [comment]
the header is not aligned with the body.
image

**Review by ChialiT — APPROVED** [review]

**Comment by kalidiagne** [comment]
- Fix Alignment Header with the body
Screenshot 2023-08-17 at 22 51 07


- Add no result message
Screenshot 2023-08-17 at 22 44 48


- Change “show result” to “show results“ in modal
Screenshot 2023-08-17 at 22 44 58


- Decrease padding between buttons (mobile)
Screenshot 2023-08-17 at 22 43 47


- Decrease padding between tags  (mobile)
Screenshot 2023-08-17 at 22 48 47

**Review by thebeyondr — APPROVED** [review]
yeah

**Pull request merged**
