### PR TITLE
update to design v1.5

### PR DESCRIPTION
**Pull request by kalidiagne**
This PR includes updates for `design v1.5`: 

#### Progams page
- [x] Programs page update to design v1.5 
  - [x] New link accelerator programs
  - [x] Intro section copy update
  - [x] Add a new Learn More section with a CTA to bring ppl to discord
   - [x] Remove collapsible function for sections (eg Curriculum/FAQ/How To Apply) to make content more visible.
   - [x] FAQ which should remain collapsible, but closed by default
   
#### General
- [x] Sections are demarcated by a 1pt stroke of Tuatara 300

### CODE REVIEW

**Comment by ChialiT** [comment]
Looks better for me, and easier to read overall, maybe add more padding on the top of content?
image

**Review by ChialiT — APPROVED** [review]

**Comment by ChialiT** [comment]
related to #155

**Comment by kalidiagne** [comment]
> Looks better for me, and easier to read overall, maybe add more padding on the top of content? image

ty! just updated

**Review by AtHeartEngineer — APPROVED** [review]

**Comment by AtHeartEngineer** [comment]
Looks good! I like the new program page. Using dark reader it's pretty hard to read any of the text, but that's really the extensions fault

**Pull request merged**
