### PR TITLE
turn on lang. switcher

### PR DESCRIPTION
**Pull request by ChialiT**

### CODE REVIEW

**Comment by ChialiT** [comment]
@kalidiagne I turn on the lang. switcher, but the page doesn't switch to italian if I do so, and is it possible to hide lang. options that are NOT complete the translation??

thank you!

**Comment by kalidiagne** [comment]
> @kalidiagne I turn on the lang. switcher, but the page doesn't switch to italian if I do so, and is it possible to hide lang. options that are NOT complete the translation??
> 
> thank you!

Do you still have the issue? can I have more details? ( you are using a specific browser? )

I also made some changes, to allow showing only language that we enable.

@ChialiT

**Comment by ChialiT** [comment]
works now, thank you @kalidiagne

**Review by AtHeartEngineer — APPROVED** [review]

**Comment by kalidiagne** [comment]
@ChialiT mergin!

**Review by kalidiagne — APPROVED** [review]

**Pull request merged**
